=== ChrisGar/XML_FINAL/tiempo.dtd
<!ELEMENT predicciones (prediccion+)>
<!ELEMENT prediccion (realizada, ubicacion, dias)>
<!ELEMENT realizada (#PCDATA)>
<!ELEMENT ubicacion (localidad)>
<!ATTLIST ubicacion id CDATA #REQUIRED>
<!ELEMENT localidad (nombre, provincia)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT dias (dia*)>
<!ELEMENT dia (periodos, datos, uvmax?)>
<!ATTLIST dia fecha CDATA #REQUIRED>
<!ELEMENT periodos (periodo*)>
<!ELEMENT periodo (precipitaciones?, nieve?, cielo?, viento?, rachas?)>
<!ATTLIST periodo intervalo CDATA #REQUIRED>
<!ELEMENT viento (direccion, velocidad)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT velocidad (#PCDATA)>
<!ELEMENT precipitaciones (#PCDATA)>
<!ELEMENT nieve (#PCDATA)>
<!ELEMENT cielo (#PCDATA)>
<!ATTLIST cielo estado CDATA #REQUIRED>
<!ELEMENT rachas (#PCDATA)>
<!ELEMENT datos (dato*)>
<!ELEMENT dato (max, min, horas?)>
<!ATTLIST dato valor CDATA #REQUIRED>
<!ELEMENT max (#PCDATA)>
<!ELEMENT min (#PCDATA)>
<!ELEMENT horas (hora*)>
<!ELEMENT hora (#PCDATA)>
<!ATTLIST hora valor CDATA #REQUIRED>
<!ELEMENT uvmax (#PCDATA)>

=== ChrisGar/XML_FINAL/tiempo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE predicciones SYSTEM "tiempo.dtd"> -->
<predicciones>
	<prediccion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tiempo.xsd">
		<realizada>2023-03-05T10:45:21</realizada>
		<ubicacion id="03014">
			<localidad>
				<nombre>Alicante/Alacant</nombre>
				<provincia>Alacant/Alicante</provincia>
			</localidad>
		</ubicacion>
		<dias>
			<dia fecha="2023-03-05">
				<periodos>
					<periodo intervalo="00-24">
						<rachas>50</rachas>
					</periodo>
					<periodo intervalo="00-12">
						<viento>
							<direccion>S</direccion>
							<velocidad>10</velocidad>
						</viento>
						<rachas>50</rachas>
					</periodo>
					<periodo intervalo="12-24">
						<precipitaciones>80</precipitaciones>
						<nieve>1300</nieve>
						<cielo estado="44">Nuboso con lluvia escasa</cielo>
					</periodo>
					<periodo intervalo="00-06">
						<viento>
							<direccion>C</direccion>
							<velocidad>0</velocidad>
						</viento>
						<rachas>40</rachas>
					</periodo>
					<periodo intervalo="06-12">
						<precipitaciones>0</precipitaciones>
						<cielo estado="12">Poco nuboso</cielo>
						<viento>
							<direccion>S</direccion>
							<velocidad>10</velocidad>
						</viento>
						<rachas>50</rachas>
					</periodo>
					<periodo intervalo="12-18">
						<precipitaciones>0</precipitaciones>
						<cielo estado="14">Poco nuboso</cielo>
						<viento>
							<direccion>S</direccion>
							<velocidad>10</velocidad>
						</viento>
						<rachas>50</rachas>
					</periodo>
					<periodo intervalo="18-24">
						<precipitaciones>75</precipitaciones>
						<cielo estado="46n">Cubierto con lluvia escasa</cielo>
						<viento>
							<direccion>C</direccion>
							<velocidad>0</velocidad>
						</viento>
					</periodo>
				</periodos>
				<datos>
					<dato valor="temperatura">
						<max>17</max>
						<min>5</min>
						<horas>
							<hora valor="06">6</hora>
							<hora valor="12">16</hora>
							<hora valor="18">14</hora>
							<hora valor="24">11</hora>
						</horas>
					</dato>
					<dato valor="sens_termica">
						<max>17</max>
						<min>5</min>
						<horas>
							<hora valor="06">6</hora>
							<hora valor="12">16</hora>
							<hora valor="18">14</hora>
							<hora valor="24">11</hora>
						</horas>
					</dato>
					<dato valor="humedad_relativa">
						<max>80</max>
						<min>40</min>
						<horas>
							<hora valor="06">65</hora>
							<hora valor="12">40</hora>
							<hora valor="18">65</hora>
							<hora valor="24">80</hora>
						</horas>
					</dato>
				</datos>
				<uvmax>4</uvmax>
			</dia>
		</dias>
	</prediccion>
</predicciones>
