=== ChrisGar/XML_FINAL/tiempo.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="predicciones">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="prediccion" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="realizada" type="xs:dateTime"/>
							<xs:element name="ubicacion">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="localidad">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="nombre" type="xs:string"/>
													<xs:element name="provincia" type="xs:string"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="id" type="xs:integer" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="dias">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="dia" minOccurs="1" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="periodos">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="periodo" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="precipitaciones" type="xs:integer" minOccurs="0" maxOccurs="1"/>
																			<xs:element name="nieve" type="xs:integer" minOccurs="0" maxOccurs="1"/>
																			<xs:element name="cielo" minOccurs="0" maxOccurs="1">
																				<xs:complexType>
																					<xs:simpleContent>
																						<xs:extension base="xs:string">
																							<xs:attribute name="estado" type="xs:string"/>
																						</xs:extension>
																					</xs:simpleContent>
																				</xs:complexType>
																			</xs:element>
																			<xs:element name="viento" minOccurs="0" maxOccurs="1">
																				<xs:complexType>
																					<xs:sequence>
																						<xs:element name="direccion" type="xs:string"/>
																						<xs:element name="velocidad" type="xs:integer"/>
																					</xs:sequence>
																				</xs:complexType>
																			</xs:element>
																			<xs:element name="rachas" type="xs:integer" minOccurs="0" maxOccurs="1"/>
																		</xs:sequence>
																		<xs:attribute name="intervalo" type="xs:string"/>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="datos">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="dato" minOccurs="3" maxOccurs="3">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="max" type="xs:integer" minOccurs="0" maxOccurs="1"/>
																			<xs:element name="min" type="xs:integer" minOccurs="0" maxOccurs="1"/>
																			<xs:element name="horas" minOccurs="0" maxOccurs="1">
																				<xs:complexType>
																					<xs:sequence>
																						<xs:element minOccurs="4" maxOccurs="4" name="hora">
																							<xs:complexType>
																								<xs:simpleContent>
																									<xs:extension base="xs:integer">
																										<xs:attribute name="valor" type="xs:string" use="required"/>
																									</xs:extension>
																								</xs:simpleContent>
																							</xs:complexType>
																						</xs:element>
																					</xs:sequence>
																				</xs:complexType>
																			</xs:element>
																		</xs:sequence>
																		<xs:attribute name="valor" use="required">
																			<xs:simpleType>
																				<xs:restriction base="xs:string">
																					<xs:enumeration value="temperatura"/>
																					<xs:enumeration value="sens_termica"/>
																					<xs:enumeration value="humedad_relativa"/>
																				</xs:restriction>
																			</xs:simpleType>
																		</xs:attribute>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="uvmax" type="xs:integer" minOccurs="0" maxOccurs="1"/>
												</xs:sequence>
												<xs:attribute name="fecha" type="xs:date" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ChrisGar/XML_FINAL/ejemplo_propietario3_valencia.xml
<predicciones xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tiempo.xsd">
	<prediccion>
		<realizada>2023-03-10T07:16:42</realizada>
		<ubicacion id="46250">
			<localidad>
				<nombre>Val�ncia</nombre>
				<provincia>Val�ncia/Valencia</provincia>
			</localidad>
		</ubicacion>
		<dias>
			<dia fecha="2023-03-10">
				<periodos>
					<periodo intervalo="00-24">
						<precipitaciones>0</precipitaciones>
						<cielo estado="Nubes altas">17</cielo>
						<viento>
							<direccion>O</direccion>
							<velocidad>20</velocidad>
						</viento>
					</periodo>
					<periodo intervalo="00-12">
						<precipitaciones>0</precipitaciones>
						<cielo estado="Nubes altas">17</cielo>
						<viento>
							<direccion>O</direccion>
							<velocidad>30</velocidad>
						</viento>
					</periodo>
					<periodo intervalo="12-24">
						<precipitaciones>0</precipitaciones>
						<cielo estado="Nubes altas">17</cielo>
						<viento>
							<direccion>O</direccion>
							<velocidad>20</velocidad>
						</viento>
					</periodo>
					<periodo intervalo="00-06">
						<precipitaciones>0</precipitaciones>
						<cielo estado="Nubes altas">17n</cielo>
						<viento>
							<direccion>O</direccion>
							<velocidad>30</velocidad>
						</viento>
					</periodo>
					<periodo intervalo="06-12">
						<precipitaciones>0</precipitaciones>
						<cielo estado="Nubes altas">17</cielo>
						<viento>
							<direccion>O</direccion>
							<velocidad>20</velocidad>
						</viento>
					</periodo>
					<periodo intervalo="12-18">
						<precipitaciones>0</precipitaciones>
						<cielo estado="Nubes altas">17</cielo>
						<viento>
							<direccion>O</direccion>
							<velocidad>15</velocidad>
						</viento>
					</periodo>
					<periodo intervalo="18-24">
						<precipitaciones>0</precipitaciones>
						<cielo estado="Poco nuboso">12n</cielo>
						<viento>
							<direccion>O</direccion>
							<velocidad>10</velocidad>
						</viento>
					</periodo>
				</periodos>
				<datos>
					<dato valor="temperatura">
						<max>26</max>
						<min>16</min>
						<horas>
							<hora valor="06">17</hora>
							<hora valor="12">24</hora>
							<hora valor="18">25</hora>
							<hora valor="24">20</hora>
						</horas>
					</dato>
					<dato valor="sens_termica">
						<max>27</max>
						<min>16</min>
						<horas>
							<hora valor="06">17</hora>
							<hora valor="12">24</hora>
							<hora valor="18">25</hora>
							<hora valor="24">20</hora>
						</horas>
					</dato>
					<dato valor="humedad_relativa">
						<max>50</max>
						<min>25</min>
						<horas>
							<hora valor="06">50</hora>
							<hora valor="12">30</hora>
							<hora valor="18">30</hora>
							<hora valor="24">40</hora>
						</horas>
					</dato>
				</datos>
				<uvmax>5</uvmax>
			</dia>
			<dia fecha="2023-03-11">
				<periodos>
					<periodo intervalo="00-24">
						<precipitaciones>0</precipitaciones>
						<cielo estado="Poco nuboso">12</cielo>
						<viento>
							<direccion>O</direccion>
							<velocidad>25</velocidad>
						</viento>
					</periodo>
					<periodo intervalo="00-12">
						<precipitaciones>0</precipitaciones>
						<cielo estado="Poco nuboso">12</cielo>
						<viento>
							<direccion>O</direccion>
							<velocidad>25</velocidad>
						</viento>
					</periodo>
					<periodo intervalo="12-24">
						<precipitaciones>0</precipitaciones>
						<cielo estado="Poco nuboso">12</cielo>
						<viento>
							<direccion>O</direccion>
							<velocidad>25</velocidad>
						</viento>
					</periodo>
					<periodo intervalo="00-06">
						<precipitaciones>0</precipitaciones>
						<cielo estado="Poco nuboso">12n</cielo>
						<viento>
							<direccion>SO</direccion>
							<velocidad>10</velocidad>
						</viento>
					</periodo>
					<periodo intervalo="06-12">
						<precipitaciones>0</precipitaciones>
						<cielo estado="Poco nuboso">12</cielo>
						<viento>
							<direccion>O</direccion>
							<velocidad>25</velocidad>
						</viento>
					</periodo>
					<periodo intervalo="12-18">
						<precipitaciones>0</precipitaciones>
						<cielo estado="Poco nuboso">12</cielo>
						<viento>
							<direccion>NO</direccion>
							<velocidad>25</velocidad>
						</viento>
					</periodo>
					<periodo intervalo="18-24">
						<precipitaciones>0</precipitaciones>
						<cielo estado="Nubes altas">17n</cielo>
						<viento>
							<direccion>NO</direccion>
							<velocidad>15</velocidad>
						</viento>
					</periodo>
				</periodos>
				<datos>
					<dato valor="temperatura">
						<max>31</max>
						<min>18</min>
						<horas>
							<hora valor="06">18</hora>
							<hora valor="12">27</hora>
							<hora valor="18">27</hora>
							<hora valor="24">20</hora>
						</horas>
					</dato>
					<dato valor="sens_termica">
						<max>31</max>
						<min>18</min>
						<horas>
							<hora valor="06">18</hora>
							<hora valor="12">27</hora>
							<hora valor="18">27</hora>
							<hora valor="24">20</hora>
						</horas>
					</dato>
					<dato valor="humedad_relativa">
						<max>60</max>
						<min>20</min>
						<horas>
							<hora valor="06">60</hora>
							<hora valor="12">25</hora>
							<hora valor="18">25</hora>
							<hora valor="24">40</hora>
						</horas>
					</dato>
				</datos>
				<uvmax>5</uvmax>
			</dia>
			<dia fecha="2023-03-12">
				<periodos>
					<periodo intervalo="00-24">
						<precipitaciones>0</precipitaciones>
						<cielo estado="Poco nuboso">12</cielo>
						<viento>
							<direccion>SE</direccion>
							<velocidad>10</velocidad>
						</viento>
					</periodo>
					<periodo intervalo="00-12">
						<precipitaciones>0</precipitaciones>
						<cielo estado="Poco nuboso">12</cielo>
						<viento>
							<direccion>NO</direccion>
							<velocidad>15</velocidad>
						</viento>
					</periodo>
					<periodo intervalo="12-24">
						<precipitaciones>0</precipitaciones>
						<cielo estado="Poco nuboso">12</cielo>
						<viento>
							<direccion>SE</direccion>
							<velocidad>10</velocidad>
						</viento>
					</periodo>
				</periodos>
				<datos>
					<dato valor="temperatura">
						<max>28</max>
						<min>16</min>
					</dato>
					<dato valor="sens_termica">
						<max>28</max>
						<min>16</min>
					</dato>
					<dato valor="humedad_relativa">
						<max>70</max>
						<min>30</min>
					</dato>
				</datos>
				<uvmax>5</uvmax>
			</dia>
			<dia fecha="2023-03-13">
				<periodos>
					<periodo intervalo="00-24">
						<precipitaciones>0</precipitaciones>
						<cielo estado="Poco nuboso">12</cielo>
						<viento>
							<direccion>SO</direccion>
							<velocidad>20</velocidad>
						</viento>
					</periodo>
					<periodo intervalo="00-12">
						<precipitaciones>0</precipitaciones>
						<cielo estado="Nubes altas">17</cielo>
						<viento>
							<direccion>SO</direccion>
							<velocidad>20</velocidad>
						</viento>
					</periodo>
					<periodo intervalo="12-24">
						<precipitaciones>0</precipitaciones>
						<cielo estado="Poco nuboso">12</cielo>
						<viento>
							<direccion>O</direccion>
							<velocidad>25</velocidad>
						</viento>
					</periodo>
				</periodos>
				<datos>
					<dato valor="temperatura">
						<max>31</max>
						<min>13</min>
					</dato>
					<dato valor="sens_termica">
						<max>31</max>
						<min>13</min>
					</dato>
					<dato valor="humedad_relativa">
						<max>75</max>
						<min>15</min>
					</dato>
				</datos>
				<uvmax>5</uvmax>
			</dia>
			<dia fecha="2023-03-14">
				<periodos>
					<periodo intervalo="">
						<precipitaciones>0</precipitaciones>
						<cielo estado="Nubes altas">17</cielo>
						<viento>
							<direccion>SO</direccion>
							<velocidad>10</velocidad>
						</viento>
					</periodo>
				</periodos>
				<datos>
					<dato valor="temperatura">
						<max>25</max>
						<min>14</min>
					</dato>
					<dato valor="sens_termica">
						<max>25</max>
						<min>14</min>
					</dato>
					<dato valor="humedad_relativa">
						<max>50</max>
						<min>20</min>
					</dato>
				</datos>
				<uvmax>4</uvmax>
			</dia>
			<dia fecha="2023-03-15">
				<periodos>
					<periodo intervalo="">
						<precipitaciones>0</precipitaciones>
						<cielo estado="Poco nuboso">12</cielo>
						<viento>
							<direccion>SE</direccion>
							<velocidad>15</velocidad>
						</viento>
					</periodo>
				</periodos>
				<datos>
					<dato valor="temperatura">
						<max>22</max>
						<min>11</min>
					</dato>
					<dato valor="sens_termica">
						<max>22</max>
						<min>11</min>
					</dato>
					<dato valor="humedad_relativa">
						<max>75</max>
						<min>35</min>
					</dato>
				</datos>
			</dia>
			<dia fecha="2023-03-16">
				<periodos>
					<periodo intervalo="">
						<precipitaciones>0</precipitaciones>
						<cielo estado="Poco nuboso">12</cielo>
						<viento>
							<direccion>E</direccion>
							<velocidad>15</velocidad>
						</viento>
					</periodo>
				</periodos>
				<datos>
					<dato valor="temperatura">
						<max>21</max>
						<min>9</min>
					</dato>
					<dato valor="sens_termica">
						<max>21</max>
						<min>9</min>
					</dato>
					<dato valor="humedad_relativa">
						<max>75</max>
						<min>55</min>
					</dato>
				</datos>
			</dia>
		</dias>
	</prediccion>
</predicciones>

=== ChrisGar/XML_FINAL/ejemplo_propietario1_alicante.xml
<predicciones
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tiempo.xsd">
	<prediccion>
		<realizada>2023-03-05T10:45:21</realizada>
		<ubicacion id="03014">
			<localidad>
				<nombre>Alicante/Alacant</nombre>
				<provincia>Alacant/Alicante</provincia>
			</localidad>
		</ubicacion>
		<dias>
			<dia fecha="2023-03-05">
				<periodos>
					<periodo intervalo="00-24"></periodo>
					<periodo intervalo="00-12"></periodo>
					<periodo intervalo="12-24">
						<precipitaciones>80</precipitaciones>
						<nieve>1300</nieve>
						<cielo estado="Nuboso con lluvia escasa">44</cielo>
						<viento>
							<direccion>S</direccion>
							<velocidad>10</velocidad>
						</viento>
					</periodo>
					<periodo intervalo="00-06">
						<viento>
							<direccion>C</direccion>
							<velocidad>0</velocidad>
						</viento>
					</periodo>
					<periodo intervalo="06-12">
						<precipitaciones>0</precipitaciones>
						<cielo estado="Poco nuboso">12</cielo>
						<viento>
							<direccion>S</direccion>
							<velocidad>10</velocidad>
						</viento>
					</periodo>
					<periodo intervalo="12-18">
						<precipitaciones>0</precipitaciones>
						<cielo estado="Nuboso">14</cielo>
						<viento>
							<direccion>S</direccion>
							<velocidad>10</velocidad>
						</viento>
					</periodo>
					<periodo intervalo="18-24">
						<precipitaciones>75</precipitaciones>
						<nieve>1300</nieve>
						<cielo estado="Cubierto con lluvia escasa">46n</cielo>
						<viento>
							<direccion>C</direccion>
							<velocidad>0</velocidad>
						</viento>
					</periodo>
				</periodos>
				<datos>
					<dato valor="temperatura">
						<max>17</max>
						<min>5</min>
						<horas>
							<hora valor="06">6</hora>
							<hora valor="12">16</hora>
							<hora valor="18">14</hora>
							<hora valor="24">11</hora>
						</horas>
					</dato>
					<dato valor="sens_termica">
						<max>17</max>
						<min>5</min>
						<horas>
							<hora valor="06">6</hora>
							<hora valor="12">16</hora>
							<hora valor="18">14</hora>
							<hora valor="24">11</hora>
						</horas>
					</dato>
					<dato valor="humedad_relativa">
						<max>80</max>
						<min>40</min>
						<horas>
							<hora valor="06">65</hora>
							<hora valor="12">40</hora>
							<hora valor="18">65</hora>
							<hora valor="24">80</hora>
						</horas>
					</dato>
				</datos>
				<uvmax>4</uvmax>
			</dia>
			<dia fecha="2023-03-06">
				<periodos>
					<periodo intervalo="00-24">
						<precipitaciones>45</precipitaciones>
						<nieve>1500</nieve>
						<cielo estado="Intervalos nubosos">13</cielo>
						<viento>
							<direccion>NO</direccion>
							<velocidad>30</velocidad>
						</viento>
					</periodo>
					<periodo intervalo="00-12">
						<precipitaciones>30</precipitaciones>
						<cielo estado="Intervalos nubosos">13</cielo>
						<viento>
							<direccion>NO</direccion>
							<velocidad>30</velocidad>
						</viento>
					</periodo>
					<periodo intervalo="12-24">
						<precipitaciones>20</precipitaciones>
						<nieve>1500</nieve>
						<cielo estado="Muy nuboso">15</cielo>
						<viento>
							<direccion>NO</direccion>
							<velocidad>30</velocidad>
						</viento>
					</periodo>
					<periodo intervalo="00-06">
						<precipitaciones>30</precipitaciones>
						<nieve>1400</nieve>
						<cielo estado="Nuboso">14n</cielo>
						<viento>
							<direccion>O</direccion>
							<velocidad>10</velocidad>
						</viento>
					</periodo>
					<periodo intervalo="06-12">
						<precipitaciones>0</precipitaciones>
						<cielo estado="Poco nuboso">12</cielo>
						<viento>
							<direccion>NO</direccion>
							<velocidad>30</velocidad>
						</viento>
					</periodo>
					<periodo intervalo="12-18">
						<precipitaciones>0</precipitaciones>
						<cielo estado="Muy nuboso">15</cielo>
						<viento>
							<direccion>NO</direccion>
							<velocidad>20</velocidad>
						</viento>
					</periodo>
					<periodo intervalo="18-24">
						<precipitaciones>20</precipitaciones>
						<cielo estado="Nuboso">14n</cielo>
						<viento>
							<direccion>C</direccion>
							<velocidad>0</velocidad>
						</viento>
					</periodo>
				</periodos>
				<datos>
					<dato valor="temperatura">
						<max>22</max>
						<min>10</min>
						<horas>
							<hora valor="06">10</hora>
							<hora valor="12">20</hora>
							<hora valor="18">18</hora>
							<hora valor="24">14</hora>
						</horas>
					</dato>
					<dato valor="sens_termica">
						<max>22</max>
						<min>8</min>
						<horas>
							<hora valor="06">10</hora>
							<hora valor="12">20</hora>
							<hora valor="18">18</hora>
							<hora valor="24">14</hora>
						</horas>
					</dato>
					<dato valor="humedad_relativa">
						<max>85</max>
						<min>30</min>
						<horas>
							<hora valor="06">75</hora>
							<hora valor="12">35</hora>
							<hora valor="18">40</hora>
							<hora valor="24">60</hora>
						</horas>
					</dato>
				</datos>
				<uvmax>4</uvmax>
			</dia>
			<dia fecha="2023-03-07">
				<periodos>
					<periodo intervalo="00-24">
						<precipitaciones>45</precipitaciones>
						<cielo estado="Intervalos nubosos">13</cielo>
						<viento>
							<direccion>O</direccion>
							<velocidad>20</velocidad>
						</viento>
					</periodo>
					<periodo intervalo="00-12">
						<precipitaciones>45</precipitaciones>
						<cielo estado="Intervalos nubosos">13</cielo>
						<viento>
							<direccion>O</direccion>
							<velocidad>20</velocidad>
						</viento>
					</periodo>
					<periodo intervalo="12-24">
						<precipitaciones>5</precipitaciones>
						<cielo estado="Nubes altas">17</cielo>
						<viento>
							<direccion>O</direccion>
							<velocidad>20</velocidad>
						</viento>
					</periodo>
				</periodos>
				<datos>
					<dato valor="temperatura">
						<max>24</max>
						<min>11</min>
					</dato>
					<dato valor="sens_termica">
						<max>24</max>
						<min>11</min>
					</dato>
					<dato valor="humedad_relativa">
						<max>80</max>
						<min>25</min>
					</dato>
				</datos>
				<uvmax>4</uvmax>
			</dia>
			<dia fecha="2023-03-08">
				<periodos>
					<periodo intervalo="00-24">
						<precipitaciones>0</precipitaciones>
						<cielo estado="Nubes altas">17</cielo>
						<viento>
							<direccion>S</direccion>
							<velocidad>20</velocidad>
						</viento>
					</periodo>
					<periodo intervalo="00-12">
						<precipitaciones>0</precipitaciones>
						<cielo estado="Nubes altas">17</cielo>
						<viento>
							<direccion>S</direccion>
							<velocidad>20</velocidad>
						</viento>
					</periodo>
					<periodo intervalo="12-24">
						<precipitaciones>0</precipitaciones>
						<cielo estado="Nubes altas">17</cielo>
						<viento>
							<direccion>S</direccion>
							<velocidad>20</velocidad>
						</viento>
					</periodo>
				</periodos>
				<datos>
					<dato valor="temperatura">
						<max>24</max>
						<min>11</min>
					</dato>
					<dato valor="sens_termica">
						<max>24</max>
						<min>11</min>
					</dato>
					<dato valor="humedad_relativa">
						<max>65</max>
						<min>40</min>
					</dato>
				</datos>
				<uvmax>5</uvmax>
			</dia>
			<dia fecha="2023-03-09">
				<periodos>
					<periodo intervalo="">
						<precipitaciones>5</precipitaciones>
						<cielo estado="Poco nuboso">12</cielo>
						<viento>
							<direccion>O</direccion>
							<velocidad>25</velocidad>
						</viento>
					</periodo>
				</periodos>
				<datos>
					<dato valor="temperatura">
						<max>27</max>
						<min>15</min>
					</dato>
					<dato valor="sens_termica">
						<max>27</max>
						<min>15</min>
					</dato>
					<dato valor="humedad_relativa">
						<max>80</max>
						<min>30</min>
					</dato>
				</datos>
				<uvmax>5</uvmax>
			</dia>
			<dia fecha="2023-03-10">
				<periodos>
					<periodo intervalo="">
						<precipitaciones>0</precipitaciones>
						<cielo estado="Nubes altas">17</cielo>
						<viento>
							<direccion>S</direccion>
							<velocidad>15</velocidad>
						</viento>
					</periodo>
				</periodos>
				<datos>
					<dato valor="temperatura">
						<max>25</max>
						<min>14</min>
					</dato>
					<dato valor="sens_termica">
						<max>25</max>
						<min>14</min>
					</dato>
					<dato valor="humedad_relativa">
						<max>55</max>
						<min>30</min>
					</dato>
				</datos>
			</dia>
			<dia fecha="2023-03-11">
				<periodos>
					<periodo intervalo="">
						<precipitaciones>0</precipitaciones>
						<cielo estado="Nubes altas">17</cielo>
						<viento>
							<direccion>SO</direccion>
							<velocidad>5</velocidad>
						</viento>
					</periodo>
				</periodos>
				<datos>
					<dato valor="temperatura">
						<max>31</max>
						<min>15</min>
					</dato>
					<dato valor="sens_termica">
						<max>31</max>
						<min>15</min>
					</dato>
					<dato valor="humedad_relativa">
						<max>55</max>
						<min>20</min>
					</dato>
				</datos>
			</dia>
		</dias>
	</prediccion>
</predicciones>
